{{- if .Values.sandbox.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "mlchain.sandbox.fullname" . }}
type: Opaque
data:
  {{- include "mlchain.sandbox.credentials" . | nindent 2 }}
{{- end }}
