{{- if .Values.ssrfProxy.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "mlchain.ssrfProxy.fullname" . }}
data:
  squid.conf: |-
    {{- include "mlchain.ssrfProxy.config.squid" . | indent 4 }}
{{- end }}
