{{- if and .Values.worker.enabled}}
{{- $usePvc := not (or .Values.externalS3.enabled .Values.externalOSS.enabled .Values.externalAzureBlobStorage.enabled) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
{{ include "mlchain.ud.annotations" . | indent 4 }}
    descriptions: worker
  labels:
{{- include "mlchain.labels" . | nindent 4 }}
    component: worker
    # app: {{ template "mlchain.worker.fullname" . }}
{{ include "mlchain.ud.labels" . | indent 4 }}
  name: {{ template "mlchain.worker.fullname" . }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
{{- include "mlchain.selectorLabels" . | nindent 6 }}
      component: worker
      {{/*
      # Required labels for istio
      # app: {{ template "mlchain.worker.fullname" . }}
      # version: {{ (print "v" .Values.serviceMesh.version) | quote }}
      */}}
  template:
    metadata:
      annotations:
{{ include "mlchain.ud.annotations" . | indent 8 }}
      labels:
{{- include "mlchain.selectorLabels" . | nindent 8 }}
        component: worker
        {{/*
        # Required labels for istio
        # app: {{ template "mlchain.worker.fullname" . }}
        # version: {{ (print "v" .Values.serviceMesh.version) | quote }}
        */}}
{{ include "mlchain.ud.labels" . | indent 8 }}
    spec:
      {{- if .Values.image.api.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.image.api.pullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
      - image: "{{ .Values.image.api.repository }}:{{ .Values.image.api.tag }}"
        imagePullPolicy: "{{ .Values.image.api.pullPolicy }}"
        name: worker
        env:
        {{- if .Values.worker.extraEnv }}
          {{- toYaml .Values.worker.extraEnv | nindent 8 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ template "mlchain.worker.fullname" . }}
        - secretRef:
            name: {{ template "mlchain.worker.fullname" . }}
        resources:
          {{- toYaml .Values.worker.resources | nindent 12 }}
        volumeMounts:
        {{- if $usePvc }}
        - name: app-data
          mountPath: {{ .Values.api.persistence.mountPath | quote }}
          subPath: {{ .Values.api.persistence.persistentVolumeClaim.subPath | default "" }}
        {{- end }}
    {{- if and (.Values.nodeSelector) (not .Values.worker.nodeSelector) }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
    {{- end }}
    {{- if .Values.worker.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.worker.nodeSelector | indent 8 }}
    {{- end }}
    {{- if and (.Values.affinity) (not .Values.worker.affinity) }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
    {{- end }}
    {{- if .Values.worker.affinity }}
      affinity:
{{ toYaml .Values.worker.affinity | indent 8 }}
    {{- end }}
    {{- if and (.Values.tolerations) (not .Values.worker.tolerations) }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
    {{- end }}
    {{- if .Values.worker.tolerations }}
      tolerations:
{{ toYaml .Values.worker.tolerations | indent 8 }}
    {{- end }}
      volumes:
      {{- if $usePvc }}
      - name: app-data
        persistentVolumeClaim:
          claimName: {{ .Values.api.persistence.persistentVolumeClaim.existingClaim | default (printf "%s" (include "mlchain.fullname" . | trunc 58)) }}
      {{- end }}
{{- end }}